### ISSUE TITLE
how to add jdbc driver

### ISSUE THREAD

**Issue by fieder** [bitnami/bitnami-docker-tomcat#61]
I'm trying to start Tomcat with a connection to another container which runs Mysql.

At the moment I'm getting 
` java.sql.SQLException: Unable to load class: com.mysql.jdbc.Driver from ClassLoader:java.net.URLClassLoader@1be6f5c3;ClassLoader:WebappClassLoader

`
I have 2 jars I need to copy inside /tomcat/lib so they are in the classpath
- mysql-connector-java-5.1.18.jar
- tomcat-jdbc.jar

How do I add these two into tomcat container ? I need the internal path within the tomcat container to map a volume I guess...

Thank you!

**Comment by sameersbn** [comment]
@fieder The internal path is `/opt/bitnami/tomcat/lib/`. However, mounting a volume at this path will break the installation. I recommend that you extend the bitnami/tomcat image to add the required jar files, eg.

```dockerfile
FROM bitnami/tomcat:8.0.43-r0
COPY mysql-connector-java-5.1.41-bin.jar /opt/bitnami/tomcat/lib/
```

**Comment by sameersbn** [comment]
Alternately, Could you try editing the `shared.loader` parameter present in `/bitnami/tomcat/conf/catalina.properties` to specify a path for additional libs. 

For example,

```bash
# terminal 1, start tomcat
$ docker run -it --rm --name tomcat --env TOMCAT_PASSWORD=password --publish 8080:8080 --volume $PWD/data/tomcat:/bitnami/tomcat bitnami/tomcat 

# terminal 2, copy the required files into a /bitnami/tomcat/shared-libs directory
$ docker exec tomcat mkdir -p /bitnami/tomcat/shared-libs/
$ docker cp mysql-connector-java-5.1.41-bin.jar tomcat:/bitnami/tomcat/shared-libs/

# Update the tomcat configuration to pick the modules from /bitnami/tomcat/shared-libs 
$ docker exec -it tomcat sed -i 's|^shared.loader=|shared.loader=/bitnami/tomcat/shared-libs/|g' /bitnami/tomcat/conf/catalina.properties
$ docker exec -it tomcat chown -R tomcat:tomcat /bitnami/tomcat/shared-libs
```
go back to terminal 2 and restart the container for the configuration changes to take effect

P.S. For the configuration changes to persist, a volume should be mounted at the `/bitnami/tomcat` path. 

Please let us know if this configuration helped resolve the issue. If yes, we will consider adding the configuration changes to the tomcat configs by default.

**Comment by fieder** [comment]
I'm using docker compose so actually when I start, I run all containers in yml. Would your second approach still work you reckon?

**Comment by fieder** [comment]
I've tried your second approach but no lock. This is how I start the container
 
   tomcat:
    image: bitnami/tomcat:8.0.43-r0
    ports:
      - "9090:9090"
    volumes:
      - ./data/tomcat:/bitnami/tomcat
         environment:
      - JAVA_OPTS=-Denvironment=localhost -Dspring.profiles.active=localhost
      - TOMCAT_USERNAME=my_user
      - TOMCAT_PASSWORD=my_password
      - TOMCAT_HTTP_PORT=9090
    links:
      - mysqldb

I've done what you explained which is 
1. create a folder : */bitnami/tomcat/shared-libs/*
2. copy 2 jars into it (mysql-connector-java-5.1.18.jar and tomcat-jdbc.jar)
3. change *catalina.properties* so that *shared.loader* points to  */bitnami/tomcat/shared-libs/* which contains the jars I need.
4. Change folder permissions on  */bitnami/tomcat/shared-libs/* so that *tomcat* user is the owner.
5. Restart container

I can see changes do take effect. In my local folder mapped to */bitnami/tomcat/shared-libs* I can see the 2 jars and also permission is set tomcat:tomcat for the container folder (shared-libs) and the jars. On top of that *catalina.properties* does contain the right path *shared.loader=/bitnami/tomcat/shared-libs/* so far so good.

The connection to MySQL is specified in /conf/context.xml

```
<Resource name="jdbc/havefun"
              type="javax.sql.DataSource"
              factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
              maxWait="10000"
              username="havefun"
              password="havefun"
              driverClassName="com.mysql.jdbc.Driver"
              url="jdbc:mysql://mysqldb:3306/havefun?useUnicode=true&amp;characterEncoding=utf8"
              initialSize="10"
              maxActive="100"
              maxIdle="50"
              minIdle="10"/>
```

The error though remains the same

```
Caused by: java.lang.ClassNotFoundException: Unable to load class: com.mysql.jdbc.Driver from ClassLoader:java.net.URLClassLoader@1be6f5c3;ClassLoader:WebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@658d046a

        at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:56)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:268)
        ... 32 more
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:38)
        ... 33 more

25-Apr-2017 08:17:07.713 WARNING [localhost-startStop-1] org.apache.catalina.core.NamingContextListener.addResource Failed to register in JMX: javax.naming.NamingException: Unable to load class: com.mysql.jdbc.Driver from ClassLoader:java.net.URLClassLoader@1be6f5c3;ClassLoader:WebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@658d046a

25-Apr-2017 08:17:07.729 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /bitnami/tomcat/data/ROOT has finished in 97 ms
25-Apr-2017 08:17:07.738 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
25-Apr-2017 08:17:07.747 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
25-Apr-2017 08:17:07.750 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 2537 ms

```

Any suggestion?

**Comment by fieder** [comment]
Worth mentioning I logged into the tomcat container (*docker exec -it tomcat bash*)  and copied manually both jars from 

**/bitnami/tomcat/shared-libs**

to 

**/opt/bitnami/tomcat/lib**

and restarted the container to see whether they get picked up but no luck. Same error.

**Comment by sameersbn** [comment]
@fieder did you restart the container after copying the files?

also I would like to note that the tomcat image already has the `tomcat-jdbc.jar` package installed.'

Could you please share a sample application that i can use to test this use-case? Thanks.

**Comment by fieder** [comment]
@sameersbn yes for sure I restart the container after copying the files.

Thanks for pointing out *tomcat-jdbc.jar* is included. That leaves us with only one jar to add.

The app is hard to run isolated as it depends on many other things like MongoDB, RabbitMQ and Redis to mention a few aside MySQL. I guess the best way for you to reproduce or at least try your suggestion is by defining a database connection as a resource in the *conf/context.xml* . When you start the container you will get the class not found exception I think.

```
<Resource name="jdbc/havefun"
              type="javax.sql.DataSource"
              factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
              maxWait="10000"
              username="havefun"
              password="havefun"
              driverClassName="com.mysql.jdbc.Driver"
              url="jdbc:mysql://mysqldb:3306/havefun?useUnicode=true&amp;characterEncoding=utf8"
              initialSize="10"
              maxActive="100"
              maxIdle="50"
              minIdle="10"/>
```

**Comment by sameersbn** [comment]
@fieder sorry for the lateness of my response. were you able to resolve the issue?

**Comment by fieder** [comment]
Thanks for reaching out. At the end we managed to make it work but with the official tomcat:8.0.44-jre8 image.
