### ISSUE TITLE
start tomcat users is “tomcat”   i want use "root"

### ISSUE THREAD

**Issue by arsenalpoll** [bitnami/bitnami-docker-tomcat#67]
hi;
   i want use "root" to  start tomcat
   how to edit Dockerfile？

**Comment by tompizmor** [comment]
Hi @arsenalpoll,

May I ask why do you want to start tomcat as `root` user instead of `tomcat`? Running services as root users is a security issue. 

Normally services run as an unprivileged user and the permissions of some folders are set so this unprivileged user can read/write.

**Comment by arsenalpoll** [comment]
Hi @tompizmor 
Because  start XXX.war  need to create  /onput/cache   /logs files .
I need  `docker exec tomcat mkdir -p  /onput/cache   /logs &&  \
docker exec tomcat chown -R tomcat:tomcat /onput/cache  /logs &&  \
docker restart tomcat   `

I do not want to create it manually ！

**Comment by javsalgar** [comment]
Hi,

Would it make sense to create these folders in the Dockerfile itself for example?

Another option would be to add a custom entrypoint script that performs that operation and then calls the default entrypoint.
