### ISSUE TITLE
can't change user run on container bitnami tomcat

### ISSUE THREAD

**Issue by oojiact** [bitnami/bitnami-docker-tomcat#70]
i need run user docker on container

>>
in Dockerfile
FROM bitnami/tomcat
RUN groupadd -g 1999 docker && useradd -u 1999 docker -g 1999

and set docker-compose.yml
version: '2'
services:
  tomcat:
    **user: docker**
    image: bitnami/tomcat
    container_name: bitnami
    environment:
       - 'NAMI_LOG_LEVEL=trace'
    ports:
       - 8080:8080
    privileged: true

have error 

bitnami1  | 
bitnami1  | Welcome to the Bitnami tomcat container
bitnami1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tomcat
bitnami1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tomcat/issues
bitnami1  | Send us your feedback at containers@bitnami.com
bitnami1  | 
bitnami1  | INFO  ==> Starting tomcat... 
**bitnami1  | nami    ERROR Cannot find any module matching the provided specification 'tomcat'
bitnami1  | nami    TRACE Error: Cannot find any module matching the provided specification 'tomcat'
bitnami1  |     at Manager.search (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:158:13)
bitnami1  |     at Command.serviceCmds.(anonymous function).parser.addCommand.callback** (/opt/bitnami/nami/cli/nami-app.js:555:39)
bitnami1  |     at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:518:30)
bitnami1  |     at NamiParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:742:14)
bitnami1  |     at NamiCliApp.parse (/opt/bitnami/nami/cli/nami-app.js:592:17)
bitnami1  |     at NamiCliApp.exec (/opt/bitnami/nami/cli/nami-app.js:599:12)
bitnami1  |     at Object.<anonymous> (/opt/bitnami/nami/index.js:10:19)
bitnami1  |     at Module._compile (module.js:541:32)
bitnami1  |     at Object.Module._extensions..js (module.js:550:10)
bitnami1  |     at Module.load (module.js:458:32)
bitnami1 exited with code 1

**Comment by tompizmor** [comment]
Hello @oojiact,

I am afraid that currently is not possible to run the tomcat container with another user than `root`.

Would you let me know what do you need exactly to see if we can find a different workaround?

Do you need the container to run as `docker` user or do you need the tomcat process inside the container to run as `docker` user? Currently the container runs as `root` user and the tomcat process runs as `tomcat` user.
