### ISSUE TITLE
Script not enable roles on tomcat-users.xml

### ISSUE THREAD

**Issue by nayo** [bitnami/bitnami-docker-tomcat#72]
**Description**

Script dont create roles [manager-gui,admin-gui]
On bitnami/tomcat:latest from DockerHub
**Steps to reproduce the issue:**

1. Set environment variables user and password
2. Initialize container
3. Goto manager webapp

**Describe the results you received:**
Error misconfiguration

**Describe the results you expected:**
Access to tomcat login

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-Debian-amd64
Operating System: Debian GNU/Linux 4.3
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.95GiB
Name: parrot
ID: AYVF:ZSFU:AISM:NYLL:G6DC:RYE3:DLAE:YFSB:SEFE:EITD:GXJX:6HLP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
N/A
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
```
Over virtualBox
```

**Comment by javsalgar** [comment]
Hi,

I was able to access the manager and admin by setting this variable to 1:

```
TOMCAT_ALLOW_REMOTE_MANAGEMENT: Allow to connect to manager applications from remote addresses. Valid values are 0 and 1. Default: 0
```

![image](https://user-images.githubusercontent.com/1133777/48538929-0c214900-e8b6-11e8-8b97-3706f6e6934c.png)


![image](https://user-images.githubusercontent.com/1133777/48538940-117e9380-e8b6-11e8-8b5d-ae4b52257263.png)

![image](https://user-images.githubusercontent.com/1133777/48538960-1f341900-e8b6-11e8-8591-06348cd8c71e.png)

**Comment by nayo** [comment]
Hi, It works.  

However, I think that the variable is not correctly defined, it would be more like (or something like that): 

```
TOMCAT_ALLOW_WEB_MANAGEMENT: Allows connection via WEB to manage the applications 
```
Because it is currently understood that a rule will be created in the firewall.

**Comment by javsalgar** [comment]
Hi,

Thanks for the suggestion. We will consider it for future releases of the container. I have my concerns regarding backwards compatibility which should be addressed first.
