### ISSUE TITLE
Use Oracle JDK instead of OpenJDK

### ISSUE THREAD

**Issue by lduparc** [bitnami/bitnami-docker-tomcat#75]
Hi,

How can we change Java version to use oracle JDK instead of OpenJDK ?

Version 8 or the image is doing :
```
RUN bitnami-pkg install java-1.8.212-0 --checksum 54a18672c8b4c1a44324c607a6bc616f614a062005d5e3384f91f10ff6f6edea
```

but running `java -version` we can read `OpenJDK`...

**Comment by andresbono** [comment]
Hi @lduparc, unfortunately, we don't distribute the Oracle JDK version of Java.
