### ISSUE TITLE
conf files are not persisted

### ISSUE THREAD

**Issue by robguinness** [bitnami/bitnami-docker-tomcat#78]
**Description**

The latest images do not work according to the README, in particular how to persist configuration files. 

**Steps to reproduce the issue:**

1. docker run -v /path/to/tomcat-persistence:/bitnami bitnami/tomcat:latest
2. Ctrl-C
3. Check if conf files are in /path/to/tomcat-persistence/tomcat/

**Describe the results you received:**

Conf files are not present

**Describe the results you expected:**

Should be present.

**Additional information you deem important (e.g. issue happens only occasionally):**

In 9.0.24, there are files in the container at /bitnami/tomcat/conf, but in later versions these are not present.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Fri Apr 12 00:34:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Fri Apr 12 00:27:37 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 24
 Running: 1
 Paused: 0
 Stopped: 23
Images: 3
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.0.0-13-generic
Operating System: Ubuntu 19.04
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.85GiB
Name: localhost
ID: QKRM:4PA3:QAOP:S6K5:3Y5E:HXVG:ERM7:FISE:POYU:3FOF:SXFA:7TFS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment]
Hi @robguinness, thanks for noticing. As you mention, the README doesn't match the behavior of the container since these releases: [Debian: 9.0.13-r34, 8.5.35-r29, 8.0.53-r380, 7.0.92-r50. Oracle: 9.0.13-r35 , 8.5.35-r33, 8.0.53-r416, 7.0.92-r54](https://github.com/bitnami/bitnami-docker-tomcat#debian-9013-r34-8535-r29-8053-r380-7092-r50-oracle-9013-r35--8535-r33-8053-r416-7092-r54). We will need to update the README accordingly.

Can you tell us more about your use case? Do you want to provide your own configuration by modifying one or several files?

**Comment by andresbono** [comment]
The approach to modify the configuration files should be very similar to Apache: https://github.com/bitnami/bitnami-docker-apache#full-configuration.

**Comment by robguinness** [comment]
> Can you tell us more about your use case? Do you want to provide your own configuration by modifying one or several files?

Yes, I need to make quite a few modifications to the configuration, such as `tomcat-users.xml`.

**Comment by robguinness** [comment]
>  As you mention, the README doesn't match the behavior of the container since these releases: [Debian: 9.0.13-r34, 8.5.35-r29, 8.0.53-r380, 7.0.92-r50. Oracle: 9.0.13-r35 , 8.5.35-r33, 8.0.53-r416, 7.0.92-r54](https://github.com/bitnami/bitnami-docker-tomcat#debian-9013-r34-8535-r29-8053-r380-7092-r50-oracle-9013-r35--8535-r33-8053-r416-7092-r54).

Just another small note: When I pull bitnami/tomcat:9.0.24, it works as described in the README. This should be a later release than 9.0.13-r34, etc., right?

**Comment by andresbono** [comment]
Thanks for noticing, @robguinness. #79 updates the README.md with the new approach to mount configuration files. The files are not persisted anymore by default.

**Comment by robguinness** [comment]
Thanks!

**Comment by robguinness** [comment]
It seems that bitnami-bot has changed the README back to the outdated approach to mount configuration files (which doesn't work).

**Comment by dgomezleon** [comment]
Hello @robguinness,

Could you point me to commit that revert the changes that @andresbono implemented? I cannot find it in the README.md history.

**Comment by robguinness** [comment]
> Hello @robguinness,
> 
> Could you point me to commit that revert the changes that @andresbono implemented? I cannot find it in the README.md history.

Sorry for not getting back to you in a timely manner on this, but it seems the issue is now resolved.
