### ISSUE TITLE
Missing tomcat user

### ISSUE THREAD

**Issue by Fryuni** [bitnami/bitnami-docker-tomcat#83]
Its a simple issue, more like a question.

The user tomcat is not being created anymore since March 24. It was removed on these commits:
- https://github.com/bitnami/bitnami-docker-tomcat/commit/83d7fd7beb7bfddf1e1ad90b1967ff0294b3f0fe
- https://github.com/bitnami/bitnami-docker-tomcat/commit/09ea36912d3ab45121b3c780a8f107e3cac273e5
- https://github.com/bitnami/bitnami-docker-tomcat/commit/eb9245aeb5865ea303cb9d6923347efda9cc059c

Is there a reason to use only an unnamed user instead of tomcat?
We found it because all our build that required us to switch users during startup stopped working since we referred to tomcat instead of 1001

**Comment by Mauraza** [comment]
Hi @Fryuni,

We're moving the containers to nom-root, because non-root container images add an extra layer of security and are generally recommended for production environments. However, because they run as a non-root user, privileged tasks are typically off-limits. Learn more about non-root containers in our [docs.](https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/)

**Comment by Fryuni** [comment]
Ok, so its because the user is now being set at the base minideb image and the useradd command cannot be run during this build?

**Comment by Fryuni** [comment]
Just to be clear, it was an easy fix. We just need to do a search-and-replace for all `USER tomcat` to `USER 1001` in our dockerfiles. Its just not clear to me why would this be necessary.

Our dockerfiles looked like:
```Dockerfile
FROM bitnami/tomcat:9.0

USER root
# Install some system dependencies
USER tomcat # Had to change to USER 1001

# Copy in our application files
```

The final image is still running as a non-root user.

**Comment by Mauraza** [comment]
Some Kubernetes distributions like Openshift run the container with UUID totally random so the image needs to be prepared to run as a non-existent user because of this it is a characteristic of non-root containers.

**Comment by Fryuni** [comment]
Oh, I see. So it is not to make it implicit that the container will run with the tomcat user. Giving it a name would make people (like me) think that it can only work as that user.

Thanks!
