### ISSUE TITLE
Source project location for installed packages

### ISSUE THREAD

**Issue by AndriyKalashnykov** [bitnami/bitnami-docker-tomcat#84]
**Description**

component_unpack() downloads dependencies but there is no mentioning of the source project location that produces package or tar in the [README.md](https://github.com/bitnami/bitnami-docker-tomcat/blob/master/README.md)

**Steps to reproduce the issue:**

[Dockerfile](https://github.com/bitnami/bitnami-docker-tomcat/commit/bfca480a7173e8676777d52b1c9e47abd1bcddd3)
```Dockerfile
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "tomcat" "9.0.34-0" --checksum 3265bbbb076d08066f7bd5ae0bcbffb5c98b7b78aca857d98f2044f2e900b456
```

will download [tomcat-9.0.34-0-linux-amd64-debian-10.tar.gz](https://downloads.bitnami.com/files/stacksmith/tomcat-9.0.34-0-linux-amd64-debian-10.tar.gz)

**Describe the results you expected:**

I would expect link to the project that produces [tomcat-9.0.34-0-linux-amd64-debian-10.tar.gz](https://downloads.bitnami.com/files/stacksmith/tomcat-9.0.34-0-linux-amd64-debian-10.tar.gz) in the project [README.md](https://github.com/bitnami/bitnami-docker-tomcat/blob/master/README.md) in the same way ho 
[miniweb](https://github.com/bitnami/minideb) is mentioned

**Comment by Mauraza** [comment]
Hi @AndriyKalashnykov,
 
This is part of the process we follow to make the container. We are working to make it more transparent. But please do not hesitate to use our images inside a Dockerfile as it appears in the [README.md](https://github.com/bitnami/bitnami-docker-tomcat/blob/master/README.md#deploying-web-applications-on-tomcat) after that you can add whatever you want.

**Comment by AndriyKalashnykov** [comment]
@Mauraza Appreciate you response. Though i'm still not clear - are sources for the packages like tomcat-9.0.34-0-linux-amd64-debian-10.tar.gz available as public repository or you planning to make them available as a part or making process more transparent?

**Comment by beltran-rubo** [comment]
Hi @AndriyKalashnykov, there is not a website with a list of those tarballs but they are publicly available. If you build the container image on your side, those packages are downloaded and bundled into the image. If you uncompress them you will see that is only the Tomcat official files plus some metadata.

We will consider to make them more visible base on your request, thanks for the suggestion.
