### ISSUE TITLE
JDBC connector problem!

### ISSUE THREAD

**Issue by samuk190** [bitnami/bitnami-docker-tomcat#85]
How to install jdbc to tomcat/lib and get rid of connection reference error

**Comment by joancafom** [comment]
Hi @samuk190 

Could you please elaborate a little bit more on the issue? What are the steps to reproduce the error you mention?

**Comment by samuk190** [comment]
> Hi @samuk190
> 
> Could you please elaborate a little bit more on the issue? What are the steps to reproduce the error you mention?

I solved the issue. 
Idk why but tomcat ignore context.xml from web app folder, so it doesnt read my database config settings inside
