### ISSUE TITLE
Setting TOMCAT_AJP_PORT_NUMBER has no meaningful effect

### ISSUE THREAD

**Issue by toKrause** [bitnami/bitnami-docker-tomcat#87]
**Description**

As per the readme file Tomcat has a default port for it's AJP connector of 8009. This port might be changed by setting the `TOMCAT_AJP_PORT_NUMBER` environment variable; setting the environment variable does indeed change the initially created `server.xml`. But since the corresponding `Connector`-element in that `server.xml` is commented out, this has no real world effect.

The readme certainly does imply that AJP is enabled by default and can therefore be exposed to the host or other containers.

**Steps to reproduce the issue:**

1. Create a `docker-compose.yml` with the following content:
```yaml
version: '2'

services:
  tomcat:
    environment:
      - TOMCAT_AJP_PORT_NUMBER=9090
    image: bitnami/tomcat:8.5
    ports:
      - 8080:8080
      - 9090:9090
```

2. Run Docker Compose
```bash
docker-compose up -d
```

3. Retreive the  initially created server configuration file
```
docker cp "$(docker-compose ps tomcat | sed -n '3p' | awk '{ print $1 }')":/opt/bitnami/tomcat/conf/server.xml .
```

4. Look up the relevant section
```bash
grep -A 2 -B 3 9090 server.xml 
```

**Describe the results you received:**

The "Connector"-element that configures the AJP connector is commented out. AJP is therefore not enabled.

```xml
<!--
<Connector protocol="AJP/1.3"
           address="::1"
           port="9090"
           redirectPort="8443" />
-->
```

**Describe the results you expected:**

The AJP connector should be enabled by default; or the readme file should be updated to reflect the fact that AJP is not available by default. A description of the necessary steps to enable AJP should be provided in this case.

Replacing the entire `server.xml`  with a complete custom configuration as mentioned in the [relevant section](https://github.com/bitnami/bitnami-docker-tomcat#configuration-files) of the readme file seems to be a bit overkill for this simple and common configuration option.

**Comment by dani8art** [comment]
Hi @toKrause thank you for opening the issue,

You are right, AJP connector is commented out. We just created an internal task to fix the issue and included it in our backlog. As the impact of the issue is limited and not critical, we can’t provide an ETA. If it is important for you and you feel you can handle it and you have a chance to create a PR we would be happy to handle it.

Meanwhile, you could use this other for configuring the server https://github.com/bitnami/bitnami-docker-tomcat#configuration-files

**Comment by marcosbc** [comment]
Hi @toKrause, just wanted to let you know that we implemented the `TOMCAT_ENABLE_AJP` parameter to enable AJP, and hence solving your issue. Refer to the [Environment Variables](https://github.com/bitnami/bitnami-docker-tomcat#environment-variables) section for more info.
