### ISSUE TITLE
JDK 17

### ISSUE THREAD

**Issue by AarjavP** [bitnami/bitnami-docker-tomcat#93]
I think the latest available images are for jdk11, how can I upgrade to 17? I can make a PR but not sure of everything that would be needed.
Specifically I am looking for jdk17 with tomcat 10.0.14.

**Comment by beltran-rubo** [comment]
That is not supported right now but you can fork the repo and change the "java" line to point to the [latest version 17 and the checksum](RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "java" "17.0.1-0" --checksum f41bbe05147002c16011221d6e4ba3b3d6c29d83ed1a683f57591bb3dd528a33), and rebuild the container on your own.
