### ISSUE TITLE
Add doc to start tomcat in debug mode.

### ISSUE THREAD

**Issue by sihunqu123** [bitnami/bitnami-docker-tomcat#94]
### Name and Version

bitnami/tomcat-9

### What is the problem this feature will solve?

Enable debugging for app run in tomcat.

### What is the feature you are proposing to solve the problem?

Add doc about how to enable remote debug mode.

### What alternatives have you considered?

No.

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to add this feature? The Bitnami team will be happy to review it and provide feedback.
