### ISSUE TITLE
allow to skip deployment of default web apps

### ISSUE THREAD

**Issue by ssaarinen** [bitnami/bitnami-docker-tomcat#96]
### Name and Version

bitnami-docker-tomcat

### What is the problem this feature will solve?

possibly a flag to prevent copying default webapps that are currently always copied from /webapps_default (see e.g. https://github.com/docker-library/tomcat/pull/181 for rationale).

Also I don't quite get why README instructs to copy users own WAR-files to /webapps_default instead of directly to /webapps
> In case you want to create a custom image that already contains your application war file, you need to add it to the /opt/bitnami/tomcat/webapps_default

### What is the feature you are proposing to solve the problem?

TOMCAT_ENABLE_DEFAULT_APPS=yes (defaults: no) to enable initial copy of default webapps.

### What alternatives have you considered?

removing them from the image in custom Dockerfile

**Comment by ssaarinen** [comment]
I also stumbled to a statement (https://github.com/bitnami/bitnami-docker-tomcat/blob/df28d47a7a412ee2f4e9aec58bbe44646b0b05f7/8.5/debian-10/rootfs/opt/bitnami/scripts/tomcat/postunpack.sh#L20) about image being for development which might make deploying default apps by default more sensible choice. 

But if that really is the case I think it could be made more clear in the README also.

**Comment by juan131** [comment]
Hi @ssaarinen 

Thanks so much for this feature request, we really appreciate your feedback!

Would you like to contribute a PR adding support for this feature? Please feel free to also update the **README.md** if you consider there are areas that need to be improved.

**Comment by ssaarinen** [comment]
I could give it a shot. Is it correct to still assume that these images target mainly development purposes?

**Comment by juan131** [comment]
Hi @ssaarinen 

That was automatically done by our system, see:

- https://github.com/bitnami/bitnami-docker-tomcat/commit/3d314266ff7f62caf47d974816273391bebfd519
- https://github.com/bitnami/bitnami-docker-tomcat/commit/6b14eec4af0d64cb3975135573dc43784b8aa9b0
