### ISSUE TITLE
Need an arm64 version

### ISSUE THREAD

**Issue by mzbik** [bitnami/bitnami-docker-tomcat#99]
### Name and Version

bitnami/tomcat latest

### What is the problem this feature will solve?

x64 only forces emulation on all arm hardware for tomcat and for all servlets. Very slow.

### What is the feature you are proposing to solve the problem?

Build an arm64 container

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
